apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: react
spec:
  containers:
    - name: client
      image: node-microservice/client
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /client
          name: client-volume
  volumes:
    - name: client-volume
      hostPath:
        path: /client
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react
spec:
  type: NodePort
  selector:
    app: react
  ports:
  - port: 3000
    nodePort: 30080
