apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password

---

apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app: node
spec:
  containers:
  - name: node-app
    image: node-microservice/node-app
    imagePullPolicy: Never
